/// Flutter icons IbleIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IbleIcons
///      fonts:
///       - asset: fonts/IbleIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IbleIcons {
  IbleIcons._();

  static const _kFontFam = 'IbleIcons';
  static const dynamic _kFontPkg = null;

  static const IconData add_40x40_svg = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left_40x40_svg = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_2_40x40_svg = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData memory_verses_40x40_svg = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorites_40x40_svg = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bullet_list_2_40x40_svg = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_40x40_svg = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_56x56_svg = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bold_40x40_svg = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bullet_list_40x40_svg = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_40x40_svg = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_40x40_svg = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strikethrought_40x40_svg = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo_2_40x40_svg = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_40x40_svg = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox_40x40_svg = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link_40x40_svg = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unread_40x40_svg = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_40x40_svg = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_40x40_svg = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_40x40_svg = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData move_to_40x40_svg = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note_40x40_svg = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redo_2_40x40_svg = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin_top_40x40_svg = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_40x40_svg = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redo_40x40_svg = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_40x40_svg = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData h_40x40_svg = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData underline_40x40_svg = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo_40x40_svg = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData italic_40x40_svg = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
